### ISSUE TITLE
Gradle plugin is not consistently published to plugins.gradle.org

### ISSUE THREAD

**Issue by mnazbro** [palantir-baseline/gradle-launch-config-plugin#24]
The currently published versions seem to be:
- 3.0.1
- 0.3.0
- 0.2.0

See here: https://plugins.gradle.org/plugin/com.palantir.launch-config/3.0.1

However, the most recent version is 0.3.4. Could each release be automatically published to plugins.gradle.org to guarantee that users can pick up the latest version?

**Comment by mnazbro** [comment]
I'm closing this because the plugin has appeared to change names

**Comment by qinfchen** [comment]
yeah, the latest plugin is here :( https://plugins.gradle.org/plugin/baseline.launch-config

@zoubeiri for SA
