### ISSUE TITLE
Add whitelist/blacklist support

### ISSUE THREAD

**Issue by mingyukim** [palantir-baseline/gradle-launch-config-plugin#4]
Currently, .launch file is created for all JavaExec tasks. Whitelist/blacklist support would be very useful especially when the default JavaExec task should be overridden with more sane defaults.

**Comment by mingyukim** [comment]
Sweet. Thanks @qinfchen.

Btw, it looks like the release is made on GH, but is not published to bintray yet. https://plugins.gradle.org/m2/com/palantir/launchconfig/gradle-launch-config-plugin Do you guys plan to publish it soon?

**Comment by qinfchen** [comment]
we are fixiing the plugin name to comply with baseline gradle plugin spec.  https://github.com/palantir-baseline/gradle-launch-config-plugin/pulls
